---
- name: Uninstall python-docker system package (workaround)
  apt:
    name: python-docker
    state: absent
  become: true

- name: Install Docker system packages
  apt:
    name:
      - docker.io
      - docker-compose
      - docker-registry
    state: latest
  become: true

- name: Start Docker on boot
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
  become: true

- name: Start Docker Registry on boot
  systemd:
    name: docker-registry
    daemon_reload: yes
    state: started
    enabled: yes
  become: true
