---
- name: Uninstall python-docker system package (workaround)
  apt:
    name: python-docker
    state: absent
  become: true

- name: Uninstall docker-py python package (workaround)
  # https://github.com/ansible/ansible/issues/20492
  pip:
    name: docker-py
    state: absent
  become: true

- name: Install Docker Python packages
  pip:
    name: docker
    state: present
  become: true

- name: Add Docker apt key
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present
  become: true

- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    update_cache: yes
  become: true

- name: Install Docker system packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-compose
    - docker-ce
  become: true

- name: Start Docker on boot
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
  become: true

- import_tasks: docker-registry.yml

